import React from "react";

const Privacypolicy = () => {
  return (
    <>
      <h1 className="text-2xl md:text-3xl lg:text-4xl mx-10 md:mx-16 lg:mx-20 font-bold  text-[#262566] mt-20 md:mt-24">
        Privacy Policy
      </h1>
      <p className=" text-xl md:text-2xl text-[#262566] mt-4 mx-10 md:mx-16 lg:mx-20 ">
        Introduction
      </p>

      <div className="mx-10 md:mx-16 lg:mx-20 mt-5">
        <p className="text-medium mt-3">
          This Policy is an electronic record in terms of the Information
          Technology Act, 2000 and rules there underneath as applicable and also
          the amended provisions referring to electronic records in numerous
          statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and doesn't need
          any physical or digital signatures.
        </p>

        <p className="text-medium mt-3">
          It is revealed in accordance with the provisions of Rule three (1) of
          the Information Technology (Intermediaries guidelines) Rules, 2011
          that need publishing the rules and laws, privacy policy, and Terms of
          Use for access or usage.
        </p>

        <p className="text-medium mt-3">
          The name in ("Website"), is owned and operated by Legal257(“Company”)
          a non-public Company restricted by shares, incorporated underneath the
          provisions of the businesses Act, 2013, and having its registered
          workplace at Yashwant Plaza, Indore.
        </p>

        <p className="font-semibold mt-3">
          For the aim of this Privacy Policy (“Policy”), where the context thus
          needs,
        </p>
        <p className="text-medium mt-3">
          The term ‘You’ &‘User’ shall mean any legal person or entity accessing
          or using the services provided on this website, who is competent to
          enter into binding contracts, as per the provisions of the Indian
          Contract Act, 1872;
        </p>
        <p className="text-medium mt-3">
          The terms ‘We’, ‘Us’& ‘Our’ shall mean the website and/or the company,
          because of the context so needed.
        </p>
        <p className="text-medium mt-3">
          The terms ‘Party’ & ‘Parties’ shall severally be used to confer with
          the User and the Company individually and jointly because the context
          thus needs.
        </p>
        <p className="text-medium mt-3">
          The headings of every section in this Policy are just for the purpose
          of organizing the varied provisions under this Policy in an orderly
          manner, and shall not be utilized by any Party to interpret the
          provisions contained in any form. Further, it's specifically specified
          to the Parties that the headings shall not have any legal or written
          agreement value.
        </p>
        <p className="text-medium mt-3">
          Please browse this policy carefully to know our company’s policies &
          practices when it involves handling or coping with your data. If you
          do not agree with our policies and practices, we request and ask you
          to not use our Services or our website in any manner. By
          continuing/accessing to use our website/Platform Services, or the
          other information/services provided by us, we shall assume that you
          just have read and chosen to willingly conform to our privacy policy.
        </p>
        <p className="text-medium mt-3">
          These Policies are variable in a modification which can be subject to
          change from time to time because the need arises within the interest
          of our company to serve you better, and any usage of our
          Website/Services after we make changes or have reflected changes under
          it will be deemed to be acceptance of these changes. we expect that
          you just keep a periodic check for any such changes/updates and any
          failure to do so at your end won't hold us liable.
        </p>

        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">
          Policies related to Your Personal Information
        </p>

        <p className="text-medium mt-3">
          We collect data that may primarily identify you. It includes your
          name, age, address, and phone data, together with your identity card
          data. Since you are stepping into an agreement with the opposite Party
          we Collect data, that is the name, address, identity document, mobile
          number, and age of the opposite Party.
        </p>

        <p className="text-medium mt-3">
          In case you decide for our Startup Package which incorporates Business
          Documentation and Incorporation Pack, we might collect the information
          on the Name of the corporate, Officers, Registered workplace, Contact
          Person, Contact Details, the industry of the corporate.
          Director/Partner data, Capital data, and business details as necessary
          for the rendering of the services.
        </p>

        <p className="text-medium mt-3">
          If the User chooses to get product/services from the website, the User
          consents to permit the Company/Website to gather data concerning the
          User’s buying behaviour and trends. We conjointly collect data you
          give voluntarily in free-form text boxes on the location and through
          responses to surveys, questionnaires, and the like.
        </p>

        <p className="text-medium mt-3">
          Information concerning your activity on the Services, like your search
          queries, comments, domain names, search results are chosen, the number
          of clicks, pages viewed and therefore the order of those pages, how
          long you visited our Services, the date and time you used the
          Services, error logs, and other similar data.
        </p>

        <p className="text-medium mt-3">
          If the User chooses to post messages/reviews/feedback anyplace on the
          website, as well as but not limited to message boards, chat rooms,
          alternative message areas, etc., the User is aware that any and all
          such data provided/uploaded are going to be collected and stored by
          the company indefinitely, and that such preserved data is also used to
          resolve disputes, provide client support, troubleshoot issues, etc.,
          and that such data if requested, is also provided to judicial or
          governmental authorities of requisite jurisdiction, or otherwise used
          by the Company/Website as allowable by applicable laws.
        </p>

        <p className="text-medium mt-3">
          The User is aware that any and all data referring to the User
          collected by the corporate, whether or not or in some way provided by
          the User to the Company/Website, including however not limited to
          private correspondence like emails or letters, feedback from other
          users or third parties concerning the User’s activities or postings on
          the website, etc., is also collected and compiled by the
          Company/Website into a file/folder specifically created for / assigned
          to the User, and therefore the User hereby expressly consents to a
          similar.
        </p>

        <p className="text-medium mt-3">
          The User is aware that whereas he/she will browse some sections of the
          website while not being a registered user, bound activities (such as
          inserting an order) need the User to provide valid personal data to
          the Company/Website for the aim of registration. The User is aware
          that the contact data provided to the Company/Website is also used to
          send the User offers and promotions, whether or not support the user's
          previous orders and interests, and therefore the User herewith
          expressly consents to receive an equivalent.
        </p>

        <p className="text-medium mt-3">
          The User is aware that the Company/Website could automatically track
          bound information concerning the User-based mostly upon the User’s IP
          address and therefore the User’s behaviour on the website, and the
          User expressly consents to the same.
        </p>

        <p className="text-medium mt-3">
          Nothing contained herein shall be deemed to compel the Website/Company
          to store, upload, publish, or show in any manner
          content/reviews/surveys/feedback submitted by the User, and therefore
          the User herewith expressly authorizes the web site/Company to get rid
          of from the web site any such content, review, survey, or feedback
          submitted by the User, while not cause or being needed to give notice
          the User of a similar.
        </p>

        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">Cookies</p>

        <p className="text-medium mt-3">
          We use numerous technologies, together with “cookies”, to gather
          non­-identifiable data. A cookie is a piece of information that a
          website will send to your browser, which can then be stored on your
          computer as an anonymous tag that identifies your computer however not
          you. To boost our Service, we use cookies, sent by Legal257.in or its
          third-party vendors, or different technologies. You may control the
          impact of cookies through your browser settings, however, some options
          of Legal257.com’s Service might not work properly if your use of
          cookies is disabled.
        </p>

        <p className="text-medium mt-3">
          We can also use different technologies, usually in conjunction with
          cookies, to enhance our Service on a variety of pages of
          Legal257.com’s website.
        </p>

        <p className="text-medium mt-3">
          A un­identifiable notice of a visitor’s visit to a page on
          Legal257.com’s website is generated and recorded, and which can be
          processed by us or by our suppliers.
        </p>

        <p className="text-medium mt-3">
          To disable a number of these options, you'll disable cookies in your
          internet browser’s settings. web beacon and different technologies can
          still discover visits to those pages, however, the notices they
          generate are unnoticed and cannot be related to different
          non-identifiable cookie data. in addition, the User is aware that
          he/she may encounter ‘cookies’ or different similar devices on bound
          pages of the website that are placed by third parties or affiliates of
          the Company/Website. The User expressly agrees and acknowledges that
          the Company/Website doesn't control the utilization of such
          cookies/other devices by third parties, that the Company/Website is in
          no way answerable for the same, and that the User assumes any and
          everyone risks in this regard.
        </p>

        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">
          Sharing of Personal Information
        </p>
        <p className="text-medium mt-3">
          The User is aware that the Website/Company could share the User’s
          personal info with different company entities and affiliates to assist
          detect and prevent identity theft, fraud, and different potentially
          smuggled acts; correlate related or multiple accounts to prevent abuse
          of the Website’s services; and to facilitate joint or co-branded
          services, where such services are provided by more than one company
          entity.
        </p>

        <p className="text-medium mt-3">
          The User is aware that the Website/Company could disclose personal
          info if needed to do this by law or if the Website/Company in honesty
          believes that such disclosure is fairly necessary to reply to
          subpoenas, court orders, or different legal processes. The
          Website/Company may additionally disclose the User’s personal info to
          enforcement offices, third party rights owners, or different third
          parties if it believes that such disclosure is fairly necessary to
          enforce the Terms or Policy; reply to claims that a commercial,
          posting or different content violates the rights of a 3rd party; or
          shield the rights, property or personal safety of its users, or the
          public.
        </p>

        <p className="text-medium mt-3">
          The User is additional is made aware that the Website/Company and its
          affiliates could share/sell some or all of the User’s personal info
          with different business firms should the Company/Website (or its
          assets) attempt to merge with. Such a business entity or new entity
          can still be bound by the Terms and Policy, as is also amended from
          time to time.
        </p>

        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">Security</p>

        <p className="text-medium mt-3">
          Transactions on the website are secure and guarded. Any data entered
          by the User once transacting on the website is encrypted to guard the
          User against unintentional disclosure to 3rd parties. The User’s
          credit and debit card info isn't received, stored by, or retained by
          the company/website in any manner. This data is provided by the User
          directly to the relevant payment gateway which is allowed to handle
          the information provided and is compliant with the rules and needs of
          various banks and institutions and payment franchisees that it's
          related to.
        </p>

        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">
          Third-Party Promotions
        </p>
        <p className="text-medium mt-3">
          The User is aware that the Company/Website uses third-party
          advertising firms to serve ads to the users of the website. The User
          is aware that these firms might use data concerning the User’s visits
          to the website and alternative websites so as to produce tailor-made
          advertisements to the User. Moreover, the website might contain links
          to alternative websites that will collect in person distinctive data
          regarding the User. The Company/Website isn't liable for the privacy
          practices or the content of any of the aforesaid connected websites,
          and therefore the User expressly acknowledges the same and agrees that
          any and all risks associated are going to be borne entirely by the
          User.
        </p>
        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">
          User’s Consent
        </p>
        <p className="text-medium mt-3">
          By using the site, you consent to the collection and use of the data
          you disclose on the site, as per this Privacy Policy. If we decide to
          change our Privacy Policy, we will post those changes on this page in
          order that you are continually alert to what data we collect, its
          usage, and in which circumstances we disclose it.
        </p>
        <p className="text-medium mt-3">
          If you do not expressly agree and consent to all or any of the terms
          during this Privacy Policy document and the “Consolidated Terms of
          Use”, please don't use this website/app/platform.
        </p>
        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">Grievances</p>
        <p className="text-medium mt-3">
          In accordance with under information Technology Act, 2000 if you find
          any discrepancies or have any grievances in relevance the collection,
          storage, use, disclosure, and transfer of Your Personal info under
          this Policy or any terms of Legal257.in’s Terms of Use, Privacy
          Policy, etc. please contact
        </p>
        <p className="font-semibold mt-3">Email: legal257rgvf@gmail.com</p>
        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">
          Resolution of Dispute and Associated Jurisdiction
        </p>
        <p className="text-medium mt-3">
          Hereby, it is mentioned that you agree to the dispute resolution
          mechanism followed by Legal257 that is stated below in any cases or
          jurisdiction related to cases arising from it. The dispute will be
          resolved through a 2 step process through Alternate Dispute resolution
          mechanism. The content of this section would persist even after the
          expiry of the Policy or terms and will keep guiding the dispute
          resolution process.
        </p>
        <p className="text-medium mt-3">
          Mediation: If there is any dispute between the parties, it should be
          solved with mutual agreement amicably among the parties at mutual
          satisfaction. In case, there is no scenario of both parties coming to
          an agreement mutually in thirty(30) days of the dispute when at least
          one party is properly communicating the dispute to the other party,
          then the dispute is supposed to be solved with arbitration as
          mentioned below.
        </p>
        <p className="text-medium mt-3">
          Arbitration: In case when both the parties are not able to come to a
          mutual agreement in thirty days the span of dispute arises, then the
          company will assign an arbitrator and the same dispute will be solved
          with arbitration. The jurisdiction passed by this sole arbitrator will
          be legal and parties involved have to agree to this award by the
          arbitrator. The cost of these proceedings should be bear by the
          parties themselves. However, the sole arbitrator may direct either of
          parties to bear the cost of the proceedings and that will be liable to
          either of the parties. The arbitration shall be conducted in English
          and the seat of arbitration shall be the city of Madhya Pradesh
        </p>
        <p className="text-medium mt-3">
          All the parties involved are hereby informed that the Above rules and
          privacy policy are valid and agreed by you before you use the services
          presented in the website. In any case, the disputes and their
          jurisdiction will be governed by the laws of government of India and
          the courts of Indore have exclusive jurisdiction over any dispute
          arising between the parties.
        </p>
      </div>
    </>
  );
};

export default Privacypolicy;
