import React from "react";

const Privacypolicy = () => {
  return (
    <>
      <h1 className="text-2xl md:text-3xl lg:text-4xl mx-10 md:mx-16 lg:mx-20 font-bold  text-[#262566] mt-20 md:mt-24">
        Privacy Policy
      </h1>
      <p className=" text-xl md:text-2xl text-[#262566] mt-4 mx-10 md:mx-16 lg:mx-20 ">
        Introduction
      </p>

      <div className="mx-10 md:mx-16 lg:mx-20 mt-5">
        <p className="text-medium mt-3">
          This Policy constitutes an electronic document as per the Information
          Technology Act, 2000, and the relevant rules. It also incorporates the
          amended provisions pertaining to electronic records in various
          statutes, as updated by the Information Technology Act, 2000.
          Generated by a computer system, this electronic record does not
          necessitate any physical or digital signatures.
        </p>

        <p className="text-medium mt-3">
          In compliance with Rule 3(1) of the Information Technology
          (Intermediaries guidelines) Rules, 2011, which mandates the
          publication of rules, regulations, privacy policies, and Terms of Use
          for access or usage, this document is presented.
        </p>

        <p className="text-medium mt-3">
          The entity referred to as the "Website" is the proprietary product of
          Legal257 ("Company"), a private Company limited by shares. It is
          established under the regulations outlined in the Companies Act,
          2013..
        </p>

        <p className="font-semibold mt-3">
          For the aim of this Privacy Policy (“Policy”), where the context thus
          needs,
        </p>
        <p className="text-medium mt-3">
          The term 'User' refers to any legal entity or person accessing or
          utilizing the services provided on this website, possessing the legal
          capacity to enter into binding contracts in accordance with the
          provisions of the Indian Contract Act, 1872.
        </p>
        <p className="text-medium mt-3">
          The terms 'We,' 'Us,' and 'Our' are used to represent either the
          website or the company, as dictated by the context.
        </p>
        <p className="text-medium mt-3">
          The terms 'Party' and 'Parties' are used interchangeably to refer to
          both the User and the Company individually or collectively, depending
          on the context.
        </p>
        <p className="text-medium mt-3">
          The section headings within this Policy are solely for the purpose of
          organizing the provisions in an orderly manner and do not hold any
          interpretative or legal value. Parties are explicitly informed that
          these headings should not be used for legal or contractual
          interpretation.
        </p>
        <p className="text-medium mt-3">
          Please carefully review this policy to comprehend our company's
          policies and practices regarding the handling of your data. If you do
          not agree with our policies, we kindly ask you to refrain from using
          our Services or website. By continuing to use our website or Platform
          Services, it will be assumed that you have read and willingly agreed
          to comply with our privacy policy.
        </p>
        <p className="text-medium mt-3">
          These Policies may undergo alterations as deemed necessary for the
          continuous improvement of our services and aligning with the evolving
          needs of our company. Any modifications or updates to these Policies
          will be effective immediately upon posting, and your continued use of
          our Website/Services following such changes will signify your
          acceptance of the revised terms. We advise you to regularly review
          this section for any updates, and any failure to do so on your part
          will not hold us responsible.
        </p>

        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">
          Policies related to Your Personal Information
        </p>

        <p className="text-medium mt-3">
          We gather information that may personally identify individuals,
          encompassing details such as names, ages, addresses, and phone
          numbers, alongside identity card particulars. As part of the agreement
          between the involved parties, we collect pertinent information from
          the opposite party, including their name, address, identity document,
          mobile number, and age.
        </p>

        <p className="text-medium mt-3">
          Should you opt for our Startup Package, inclusive of Business
          Documentation and Incorporation Pack, we may acquire details related
          to the company, such as the corporate name, officers, registered
          office, contact person, contact details, and the industry in which the
          company operates. Additionally, director/partner information, capital
          details, and business specifics necessary for service provision may
          also be collected.
        </p>

        <p className="text-medium mt-3">
          In the event that a user decides to purchase products or services
          through the website, the user implicitly consents to the
          Company/Website collecting data pertaining to their purchasing
          behavior and trends. Furthermore, voluntary information provided by
          the user in free-form text boxes, survey responses, and similar
          interactions will also be collected.
        </p>

        <p className="text-medium mt-3">
          Information pertaining to user activity on the Services, including
          search queries, comments, domain names, selected search results, the
          number of clicks, pages viewed, their order, duration of the visit,
          and the date and time of service usage, will be monitored. Error logs
          and similar data may also be included in this information collection
          process.
        </p>

        <p className="text-medium mt-3">
          If users choose to share messages, reviews, or feedback anywhere on
          the platform, including but not limited to forums, chat rooms, and
          other discussion areas, they acknowledge that the provided/uploaded
          data will be collected and stored by the company indefinitely. This
          preserved information may be utilized for dispute resolution, customer
          support, issue troubleshooting, etc. Additionally, users understand
          that, if required, such data may be disclosed to judicial or
          governmental authorities as mandated by the relevant jurisdiction or
          used by the company in accordance with applicable laws.
        </p>

        <p className="text-medium mt-3">
          Users are informed that any data related to them, collected by the
          company, regardless of the source (provided by the user or others),
          such as personal correspondence (emails, letters), feedback from other
          users, or third-party comments on the user's activities, will be
          compiled into a designated file or folder assigned to that user. Users
          expressly consent to this data compilation.
        </p>

        <p className="text-medium mt-3">
          While users may browse certain sections of the platform without
          registration, specific activities, such as placing an order,
          necessitate the provision of valid personal information for
          registration purposes. Users understand that the contact information
          provided may be used to send offers and promotions, tailored to their
          previous orders and interests. Users explicitly consent to receiving
          such communications.
        </p>

        <p className="text-medium mt-3">
          Users are aware that the company may automatically track certain
          information about them based on their IP address and website behavior.
          Users expressly consent to this tracking mechanism.
        </p>

        <p className="text-medium mt-3">
          The User acknowledges that the Website/Company is not obligated to
          retain, display, or publish any content, reviews, surveys, or feedback
          submitted by the User. Consequently, the User expressly grants the
          Website/Company the authority to remove, without prior notice, any
          such content submitted by the User, without incurring any obligation
          or notification to the User.
        </p>

        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">Cookies</p>

        <p className="text-medium mt-3">
          We employ various technologies, including the use of "cookies," to
          collect non-identifiable information. A cookie is a small piece of
          data sent by a website to your browser, which is then stored on your
          computer as an anonymous tag, identifying your computer but not you
          personally. Cookies, sent by Legal257.in or its third-party vendors,
          or other technologies, are utilized to enhance our Service. You have
          the option to manage cookie settings through your browser, but
          disabling cookies may impact the functionality of certain features on
          legal257.in's Service.
        </p>

        <p className="text-medium mt-3">
          In addition to cookies, we may use other technologies, often in
          conjunction with cookies, to improve our Service across various pages
          on legal257.in's website
        </p>

        <p className="text-medium mt-3">
          We generate and record non-identifiable notices of a visitor's page
          visits on legal257.in's website. These notices may be processed by us
          or our suppliers.
        </p>

        <p className="text-medium mt-3">
          To deactivate some of these features, you can disable cookies in your
          internet browser settings. However, web beacons and other technologies
          may still track visits to these pages, generating unnoticed notices
          that cannot be linked to other non-identifiable cookie data.
          Furthermore, users should be aware that they may encounter 'cookies'
          or similar devices on specific pages of the website placed by third
          parties or affiliates of the Company/Website. The user explicitly
          agrees and acknowledges that the Company/Website does not control the
          use of such cookies/other devices by third parties, is not responsible
          for them, and assumes all associated risks.
        </p>

        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">
          Sharing of Personal Information
        </p>
        <p className="text-medium mt-3">
          The User acknowledges that the Website/Company may share the User's
          personal information with various company entities and affiliates to
          aid in the detection and prevention of identity theft, fraud, and
          other potentially illicit activities. This may include correlating
          related or multiple accounts to prevent the misuse of the Website's
          services and facilitating joint or co-branded services involving more
          than one company entity.
        </p>

        <p className="text-medium mt-3">
          Furthermore, the User understands that the Website/Company may
          disclose personal information if required by law or if the Company
          believes, in good faith, that such disclosure is reasonably necessary
          to respond to subpoenas, court orders, or other legal processes. The
          Company may also disclose the User's personal information to law
          enforcement agencies, third-party rights owners, or other third
          parties if it believes that such disclosure is reasonably necessary to
          enforce the Terms or Policy, respond to claims of a commercial,
          posting, or other content violating the rights of a third party, or
          protect the rights, property, or personal safety of its users or the
          public.
        </p>

        <p className="text-medium mt-3">
          Additionally, the User is informed that the Website/Company and its
          affiliates may share or sell some or all of the User's personal
          information with other business entities in the event that the
          Company/Website (or its assets) seeks to merge. Any such business
          entity or new entity will still be bound by the Terms and Policy, as
          amended periodically.
        </p>

        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">Security</p>

        <p className="text-medium mt-3">
          The website prioritizes the security of user transactions,
          implementing robust measures to safeguard any data provided during
          transactions. All user-entered information is encrypted, ensuring
          protection against unintentional disclosure to third parties. It is
          important to note that the company/website does not receive, store, or
          retain any credit or debit card information provided by the user.
          Instead, such sensitive data is directly transmitted to a trusted
          payment gateway, which complies with the regulations and requirements
          of various banks, institutions, and payment franchises.
        </p>

        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">
          Promotional Partnerships:
        </p>
        <p className="text-medium mt-3">
          The user acknowledges that the company/website engages third-party
          advertising firms for serving ads on the platform. These firms may
          utilize data related to the user's website visits and activities on
          other platforms to deliver personalized advertisements. Additionally,
          the website may feature links to other websites that could collect
          personally identifiable information about the user. The
          company/website explicitly disclaims responsibility for the privacy
          practices and content of these linked websites. The user acknowledges
          and accepts that any associated risks are solely their
        </p>
        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">
          User’s Consent
        </p>
        <p className="text-medium mt-3">
          Your use of this platform implies your agreement to the gathering and
          utilization of the information you provide on the site, as outlined in
          this Privacy Policy. Should any modifications be made to our Privacy
          Policy, we will promptly communicate those changes on this page to
          keep you informed about the data we collect, how it is used, and the
          circumstances under which it is disclosed.
        </p>
        <p className="text-medium mt-3">
          If you do not explicitly accept and consent to all the terms outlined
          in this Privacy Policy and the "Consolidated Terms of Use," we kindly
          request that you refrain from using this website/app/platform.
        </p>
        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">
          Resolution of Concerns
        </p>
        <p className="text-medium mt-3">
          In adherence to the Information Technology Act, 2000, if you come
          across any discrepancies or have concerns related to the collection,
          storage, usage, disclosure, and transfer of your Personal Information
          under this Policy or any terms within Legal257.in’s Terms of Use,
          Privacy Policy, etc., please reach out to us via:
        </p>
        <p className="font-semibold mt-3">Email: legal257rgvf@gmail.com</p>
        <p className=" text-xl md:text-2xl text-[#262566] mt-4  ">
          Resolution of Dispute and Associated Jurisdiction
        </p>
        <p className="text-medium mt-3">
          Please be advised that by utilizing the services provided by Legal257,
          you hereby consent to the alternative dispute resolution mechanism
          outlined below, applicable to any disputes or jurisdictional matters
          stemming from such cases. The procedures articulated in this section
          shall remain in force even beyond the expiration of the Policy or
          terms, continuing to govern the dispute resolution process.
        </p>
        <p className="text-medium mt-3">
          Collaborative Resolution: Should any dispute arise between the
          involved parties, efforts will be made to reach a resolution through
          mutual agreement in an amicable manner. The parties shall endeavor to
          satisfactorily settle the dispute within a period of thirty (30) days,
          provided that at least one party duly communicates the dispute to the
          other. In the event that an agreement remains elusive within the
          stipulated timeframe, the dispute shall proceed to the arbitration
          stage as detailed below.
        </p>
        <p className="text-medium mt-3">
          Arbitral Proceedings: If mutual agreement cannot be reached within
          thirty days of the emergence of the dispute, the company will appoint
          an arbitrator to facilitate the resolution process. The jurisdiction
          determined by the appointed arbitrator shall be legally binding, and
          the involved parties must adhere to the arbitrator's decision. The
          costs associated with these proceedings shall be borne by the
          respective parties unless the arbitrator directs one party to assume
          the expenses, in which case the designated party shall be liable. The
          arbitration proceedings shall be conducted in English, and the
          designated seat of arbitration shall be the city of Madhya Pradesh.
        </p>
        <p className="text-medium mt-3">
          All parties concerned are hereby notified that the aforementioned
          rules and privacy policy are acknowledged and accepted by you prior to
          utilizing the services offered on the website. In the event of any
          disputes, the laws of the government of India shall govern, and the
          courts of Indore shall exclusively have jurisdiction over any disputes
          arising between the parties.
        </p>
      </div>
    </>
  );
};

export default Privacypolicy;
